codebundles/k8s-argocd-application-health/README.md, codebundles/k8s-argocd-application-health/runbook.robot
I don't think I can test this in the shared env at the moment... I can configure the SLX, but the map I think now just has a bunch of placeholders, so I can no longer just run a taskset/runbook.
=> Argocd runbooks

codebundles/k8s-fluxcd-helm-health/README.md, codebundles/k8s-fluxcd-helm-health/runbook.robot
@jon-funk not sure if I'm using the raise_issues components appropriately; could use a second set of eyes here
=> add and update helm with the cli format

codebundles/k8s-podresources-health/runbook.robot, codebundles/k8s-postgres-triage/runbook.robot
- Adds resource scan for labeled pods in a namespace
- Raises an issue when pods are found without limits+requests set
- All runs an informational top on the pods
=> K8s Pod Scan

codebundles/k8s-chaos-flux/README.md, codebundles/k8s-chaos-flux/runbook.robot, codebundles/k8s-pvc-healthcheck/README.md
Resolves #20  and is in support of https://github.com/runwhen/platform-core/issues/908
=> K8s chaos flux

codebundles/gcloud-node-preempt/README.md, codebundles/gcloud-node-preempt/runbook.robot, codebundles/gcloud-node-preempt/sli.robot
This adds a single sli & runbook to count and list the amount of nodes undergoing a preempt event
=> add gcloud node preempt

codebundles/gcloud-log-inspection/README.md, codebundles/gcloud-log-inspection/runbook.robot, codebundles/k8s-imagerollover-check/README.md, codebundles/k8s-imagerollover-check/runbook.robot, codebundles/k8s-redis-healthcheck/README.md, codebundles/k8s-redis-healthcheck/runbook.robot
- Add redis health triage taskset using redis-cli
- Add image rollover age triage task
- Add gcloud log inspection (kubernetes centric) triage taskset using gcloud cli
=> Add triage set

codebundles/curl-gmp-ingress-inspection/runbook.robot
- hardcodes quotes for config
- Adds the service name to the issue details string for personas to pick up
=> runbook tweaks for better issue hints

codebundles/cli-test/runbook.robot, codebundles/curl-http-ok/runbook.robot, codebundles/gcloud-log-inspection/runbook.robot, codebundles/gcloud-node-preempt/runbook.robot, codebundles/k8s-argocd-application-health/runbook.robot, codebundles/k8s-artifactory-health/runbook.robot, codebundles/k8s-daemonset-healthcheck/runbook.robot, codebundles/k8s-deployment-healthcheck/runbook.robot, codebundles/k8s-fluxcd-helm-health/runbook.robot, codebundles/k8s-jenkins-healthcheck/runbook.robot, codebundles/k8s-namespace-healthcheck/runbook.robot, codebundles/k8s-podresources-health/runbook.robot, codebundles/k8s-pvc-healthcheck/runbook.robot, codebundles/k8s-redis-healthcheck/runbook.robot, codebundles/k8s-statefulset-healthcheck/runbook.robot, codebundles/k8s-vault-healthcheck/runbook.robot, libraries/RW/CLI/json_parser.py, libraries/RW/CLI/stdout_parser.py
- Tweaks issue submission strings to have more detail and point to the namespace and workload if possible
- removes the hardcoded line insert into detail, this was added before the variables were exposed for insertion via robot layer
TODO: definitely need more cleanup and de-duplication in the future as we've talked about, like the vault taskset having statefulset crossover
=> Issue detail tweaks

codebundles/k8s-artifactory-health/README.md, codebundles/k8s-artifactory-health/runbook.robot, codebundles/k8s-deployment-healthcheck/README.md, codebundles/k8s-deployment-healthcheck/runbook.robot, codebundles/k8s-namespace-healthcheck/README.md, codebundles/k8s-namespace-healthcheck/runbook.robot, libraries/RW/CLI/json_parser.py, libraries/RW/CLI/stdout_parser.py
- improves issues / docstrings / titles across deployment + namespace tasksets
- adds 2 new tasks to namespace triage: event anomaly detection, service log aggregation and inspection
- dedupes tasks in artifactory triage - covered by statefulset triage
=> Improvements for Issue Triage

codebundles/curl-gmp-kong-ingress-inspection/runbook.robot, codebundles/curl-gmp-nginx-ingress-inspection/runbook.robot, codebundles/gcloud-node-preempt/runbook.robot, codebundles/k8s-certmanager-healthcheck/README.md, codebundles/k8s-certmanager-healthcheck/runbook.robot, codebundles/k8s-daemonset-healthcheck/README.md, codebundles/k8s-daemonset-healthcheck/runbook.robot, codebundles/k8s-deployment-healthcheck/runbook.robot, codebundles/k8s-namespace-healthcheck/runbook.robot, codebundles/k8s-podresources-health/runbook.robot, codebundles/k8s-pvc-healthcheck/runbook.robot, codebundles/k8s-vault-healthcheck/README.md, codebundles/k8s-vault-healthcheck/runbook.robot
- tweaks issue details for demo tasks, simplify strings and add quotes to template data
=> Issue tweaks

codebundles/k8s-namespace-healthcheck/runbook.robot
adds more comprehensive pod & container troubleshooting commands
=> Ns-health-updates

codebundles/aws-eks-node-reboot/README.md, codebundles/aws-eks-node-reboot/runbook.robot
- adds codebundle for performing a health check on a eks cluster nodegroup and raising an issue if the status is not ACTIVE
=> Add EKS Nodegroup check

codebundles/k8s-deployment-healthcheck/runbook.robot, codebundles/k8s-pvc-healthcheck/README.md, codebundles/k8s-pvc-healthcheck/runbook.robot
Audits RWO storage to determine if it's on the correct node.
=> Add storage task for RWO

.github/scripts/e2e.py, .github/workflows/e2e.yml
- adds a more intelligent check to ensure the codecollection has indeed reconciled
=> Handle CC reconcile time in CI

.github/config.yaml
=> Add Bot Config

codebundles/curl-gmp-nginx-ingress-inspection/runbook.robot, libraries/RW/CLI/cli_utils.py, libraries/RW/CLI/json_parser.py, libraries/RW/CLI/stdout_parser.py
- Implements next_steps into cli parsers
- Tweaks nginx ingress to use next_steps + bugfix output
=> Implement nextsteps and tweak nginx ingress cb

.github/scripts/meta.py, codebundles/curl-gmp-kong-ingress-inspection/meta.yaml, codebundles/curl-gmp-nginx-ingress-inspection/meta.yaml, codebundles/curl-http-ok/meta.yaml, codebundles/gcloud-node-preempt/meta.yaml, codebundles/k8s-argocd-application-health/meta.yaml, codebundles/k8s-artifactory-health/meta.yaml, codebundles/k8s-certmanager-healthcheck/meta.yaml, codebundles/k8s-daemonset-healthcheck/meta.yaml, codebundles/k8s-deployment-healthcheck/meta.yaml, codebundles/k8s-fluxcd-helm-health/meta.yaml, codebundles/k8s-fluxcd-kustomization-health/meta.yaml, codebundles/k8s-image-check/meta.yaml, codebundles/k8s-ingress-healthcheck/meta.yaml, codebundles/k8s-jenkins-healthcheck/meta.yaml, codebundles/k8s-namespace-healthcheck/meta.yaml, codebundles/k8s-podresources-health/meta.yaml, codebundles/k8s-postgres-triage/meta.yaml, codebundles/k8s-pvc-healthcheck/meta.yaml, codebundles/k8s-redis-healthcheck/meta.yaml, codebundles/k8s-serviceaccount-check/meta.yaml, codebundles/k8s-statefulset-healthcheck/meta.yaml, codebundles/k8s-vault-healthcheck/meta.yaml
this adjusts the prompt on the metadata to try and generate the links with more consistent output.
=> href links

.github/workflows/pypi.yaml, .gitignore, MANIFEST.in, setup.cfg, setup.py
- add config for simple keyword package publish
- add github action that triggers on version change, producing a package to pypi for each release
=> Setup Package publish

.github/scripts/meta.py, codebundles/curl-gmp-kong-ingress-inspection/meta.yaml, codebundles/curl-gmp-nginx-ingress-inspection/meta.yaml, codebundles/curl-http-ok/meta.yaml, codebundles/gcloud-node-preempt/meta.yaml, codebundles/k8s-argocd-application-health/meta.yaml, codebundles/k8s-artifactory-health/meta.yaml, codebundles/k8s-certmanager-healthcheck/meta.yaml, codebundles/k8s-daemonset-healthcheck/meta.yaml, codebundles/k8s-deployment-healthcheck/meta.yaml, codebundles/k8s-fluxcd-helm-health/meta.yaml, codebundles/k8s-fluxcd-kustomization-health/meta.yaml, codebundles/k8s-image-check/meta.yaml, codebundles/k8s-ingress-healthcheck/meta.yaml, codebundles/k8s-jenkins-healthcheck/meta.yaml, codebundles/k8s-namespace-healthcheck/meta.yaml, codebundles/k8s-podresources-health/meta.yaml, codebundles/k8s-postgres-triage/meta.yaml, codebundles/k8s-pvc-healthcheck/meta.yaml, codebundles/k8s-redis-healthcheck/meta.yaml, codebundles/k8s-serviceaccount-check/meta.yaml, codebundles/k8s-statefulset-healthcheck/meta.yaml, codebundles/k8s-vault-healthcheck/meta.yaml
This should resolve an issue where the first element is indented differently.
=> fix a missing newline

codebundles/k8s-argocd-helm-health/README.md, codebundles/k8s-argocd-helm-health/runbook.robot
Adding codebundle (k8s-argocd-helm-health) for argoCD managed help objects
Output:
```
python@1601b3e1147f:/app/codecollection/codebundles/k8s-argocd-helm-health$ NAMESPACE=jenkins CONTEXT=sandbox-cluster-1 ro runbook.robot
==============================================================================
Runbook :: This codebundle runs a series of tasks to identify potential hel...
==============================================================================
Fetch all available ArgoCD Helm releases :: List all ArgoCD helm r... ..
ArgoCD Helm releases available: 
Name:                   jenkins
Sync Status:            Synced
Health Status:          Progressing
.
Commands Used:
kubectl get applications.argoproj.io -n jenkins --context sandbox-cluster-1 -o=json | jq -r '.items[] | …
```
=> Adding codebundle (k8s-argocd-helm-health) 

.github/workflows/pypi.yaml, MANIFEST.in, setup.py
- de-nest RW package in pypi build
=> Adjust pypi build

codebundles/curl-gmp-kong-ingress-inspection/runbook.robot, codebundles/k8s-deployment-healthcheck/runbook.robot, codebundles/k8s-image-check/runbook.robot, codebundles/k8s-namespace-healthcheck/runbook.robot, libraries/RW/NextSteps/Kubernetes/mapping.yaml, libraries/RW/NextSteps/Suggest.py
- adds nextsteps logic for k8s-namespace healthcheck
- adds nextsteps logic for gmp kong ingress ingress check
- Adds joinable nextsteps
=> Add nextsteps logic to k8s namespace and gmp kong ingress codebundles

.gitbook.yaml, GITBOOK_README.md
- adds a brief readme for the main root gitbook page
=> Create readme for gitbook page

codebundles/k8s-deployment-healthcheck/.runwhen/templates/k8s-deployment-health-taskset.yaml
There was an add and remove of config provided. Just updating the gen rules. :D 
@stewartshea @jon-funk Is there a better value to put here than an empty string?
=> Updates deployment health check gen rules to match robot file needs

codebundles/curl-http-ok/runbook.robot, codebundles/k8s-loki-healthcheck/README.md, codebundles/k8s-loki-healthcheck/runbook.robot, codebundles/k8s-prometheus-healthcheck/README.md, codebundles/k8s-prometheus-healthcheck/runbook.robot, codebundles/k8s-prometheus-healthcheck/validate_servicemonitors.sh
- Adds a triage taskset for kube prom operator
- Adds a triage taskset for loki
=> Add K8s Prometheus Triage and Loki Triage

codebundles/k8s-app-troubleshoot/README.md, codebundles/k8s-app-troubleshoot/env_check.sh, codebundles/k8s-app-troubleshoot/runbook.robot, codebundles/k8s-app-troubleshoot/sli.robot, libraries/RW/K8sApplications/__init__.py, libraries/RW/K8sApplications/k8s_applications.py, libraries/RW/K8sApplications/migrations_inspector.py, libraries/RW/K8sApplications/parsers.py, libraries/RW/K8sApplications/repository.py, libraries/RW/K8sApplications/source_code.py
- Adds new task for using advanced application models to troubleshoot source code / data issues related to exceptions in logs
- Adds SLI for monitoring application exceptions, for use with SLOs to trigger workflows
=> Add Application Troubleshooting V2

codebundles/k8s-certmanager-healthcheck/.runwhen/generation-rules/k8s-certmanager-certificates-health.yaml, codebundles/k8s-certmanager-healthcheck/runbook.robot, codebundles/k8s-pvc-healthcheck/runbook.robot, codebundles/k8s-pvc-healthcheck/storage_next_steps.sh
=> Cb touchups 1122231412

codebundles/k8s-certmanager-healthcheck/.runwhen/generation-rules/k8s-certmanager-certificates-health.yaml, codebundles/k8s-certmanager-healthcheck/.runwhen/templates/k8s-certmanager-certificate-health-taskset.yaml, codebundles/k8s-deployment-healthcheck/deployment_logs.sh
- Cleans up an existing genrule for cert-manager
- Cleans up some context usage in deployment_logs.sh to support multi-context use cases
=> Cert manager rule fixup &deployment log script fixup

codebundles/k8s-app-troubleshoot/runbook.robot, codebundles/k8s-postgres-triage/runbook.robot, codebundles/k8s-statefulset-healthcheck/runbook.robot, codebundles/k8s-statefulset-healthcheck/validate_probes.sh, codebundles/k8s-statefulset-healthcheck/workload_next_steps.sh, libraries/RW/CLI/CLI.py, libraries/RW/CLI/__init__.py, libraries/RW/CLI/local_process.py, libraries/RW/CLI/postgres_helper.py
- Improves statefulset codebundle with added issues to raise
- Adds postgres keywords and updates current postgres codebundle to use them; keywords attempt to auth to database automatically by finding the mapped creds
- tweaked app cb by adding app name to task titles
TODO: 
- gen rules (coming in separate PR)
- cleanup and move to app models if this flow is popular
- add support for various configmap patterns, just did implicit, ENV and secrets for now.
=> Add issues to statefulset and new postgres keywords

codebundles/gcloud-node-preempt/runbook.robot, codebundles/gcloud-node-preempt/sli.robot, codebundles/gcp-cloud-function-health/.runwhen/templates/gcp-cloud-function-health-slo.yaml, codebundles/k8s-deployment-gitops-gh-remediate/runbook.robot, codebundles/k8s-deployment-healthcheck/validate_probes.sh
Minor codebundle tweaks to cut down the noise or fix typos
=> Tweaks from Friday

codebundles/k8s-app-troubleshoot/runbook.robot, libraries/RW/K8sApplications/k8s_applications.py, libraries/RW/K8sApplications/parsers.py
- fixes edge case for c# parse so that filepaths are picked up in the build image
- tweaks report
=> Hotfix C# Application Troubleshoot Parse

codebundles/k8s-namespace-healthcheck/workload_next_steps.sh
adds some more next_steps match strings
=> Next steps tweaks

codebundles/k8s-gitops-gh-remediate/pvc_utilization_check.sh, codebundles/k8s-gitops-gh-remediate/runbook.robot, codebundles/k8s-gitops-gh-remediate/update_github_manifests.sh, codebundles/k8s-pvc-healthcheck/pvc_utilization_check.sh, codebundles/k8s-pvc-healthcheck/runbook.robot
- adds gitops pvc remediation 
- adds dynamic issue generation based on capacity usage
=> Storage health/remediate

libraries/RW/K8sApplications/repository.py
- fixes unhandled exception in repo object when git clone fails
=> Fix unhandled exception in repo object

codebundles/k8s-fluxcd-reconcile/.runwhen/generation-rules/k8s-fluxcd-reconcile.yaml, codebundles/k8s-fluxcd-reconcile/.runwhen/templates/k8s-fluxcd-reconcile-sli.yaml, codebundles/k8s-fluxcd-reconcile/.runwhen/templates/k8s-fluxcd-reconcile-slo.yaml, codebundles/k8s-fluxcd-reconcile/.runwhen/templates/k8s-fluxcd-reconcile-slx.yaml, codebundles/k8s-fluxcd-reconcile/.runwhen/templates/k8s-fluxcd-reconcile-taskset.yaml, codebundles/k8s-fluxcd-reconcile/README.md, codebundles/k8s-fluxcd-reconcile/flux_reconcile_report.sh, codebundles/k8s-fluxcd-reconcile/runbook.robot, codebundles/k8s-fluxcd-reconcile/sli.robot
- scans all controllers in flux-system for errors
- generates a report and summary for errors with counts and recents, separated by controller
- has sli for measuring, alerting devs to faulty manifests
=> Add fluxcd reconcile codebundle

codebundles/k8s-podresources-health/runbook.robot, codebundles/k8s-podresources-health/scan_overutilized_pods.sh
- adds a task to raise issues on pods experiencing crashes / restarts related to resource usage (simple / heuristic check)
=> Add resource check task for namespace pods

codebundles/gcp-bucket-health/.runwhen/templates/gcp-bucket-health-sli.yaml, codebundles/gcp-bucket-health/.runwhen/templates/gcp-bucket-health-slx.yaml, codebundles/gcp-bucket-health/.runwhen/templates/gcp-bucket-health-taskset.yaml, codebundles/gcp-bucket-health/bucket_ops_costs.sh, codebundles/gcp-bucket-health/runbook.robot, codebundles/gcp-bucket-health/sli.robot
Adds to the GCP Bucket Health to report on and alert on GCP bucket operations that cost $$$ (read/write / class A operations)
=> add bucket ops script, tasks, and update sli / gen rule

codebundles/k8s-chaos-namespace/oomkill_pod.sh, codebundles/k8s-chaos-workload/README.md, codebundles/k8s-chaos-workload/auth.sh, codebundles/k8s-chaos-workload/change_service_port.sh, codebundles/k8s-chaos-workload/change_service_selector.sh, codebundles/k8s-chaos-workload/expand_tmp.sh, codebundles/k8s-chaos-workload/kill_workload_pod.sh, codebundles/k8s-chaos-workload/oomkill_workload_pod.sh, codebundles/k8s-chaos-workload/runbook.robot
- adds a workload specific chaos codebundle so users can target a specific workload for testing
=> Chaos Codebundle Improvements

codebundles/k8s-namespace-healthcheck/sli.robot
This should fix an issue where completed pods are counted as not ready
=> switch cli command to use jq and allow to omit additional states such as podcompleted

README.md, codebundles/gh-actions-artifact-analysis/README.md, codebundles/gh-actions-artifact-analysis/gh_actions_artifact_analysis.sh, codebundles/gh-actions-artifact-analysis/runbook.robot, codebundles/gh-actions-artifact-analysis/sli.robot, codebundles/k8s-app-troubleshoot/README.md, libraries/RW/CLI/CLI.py
Adds a user configurable task to perform analysis of github actions artifacts, producing a metric, report, or issue.
=> Add GitHub Actions Artifact Analysis Task

libraries/RW/CLI/CLI.py
Add staging functionality for files in run_cli
=> Run cli fix

codebundles/azure-apim-health/apim_metrics.sh, codebundles/azure-apim-health/apim_policies.sh, codebundles/azure-apim-health/runbook.robot, codebundles/azure-appservice-functionapp-health/appservice_health_metric.sh
This pull request standardizes the severity levels across multiple scripts by increasing all severity values from `2` or `3` to `4`. Additionally, it introduces a new condition in the `runbook.robot` script to suppress specific issues for certain deployment categories and fixes a typo in an error message title.
* Updated severity levels from `2` or `3` to `4` in `codebundles/azure-apim-health/apim_metrics.sh` for conditions related to total requests, backend response time, CPU usage, memory usage, and capacity average. [[1]](diffhunk://#diff-61d676072d39da43b767c932639da51264af1172c7322ba7ca105a5525d5705bL284-R284) [[2]](diffhunk://#diff-61d676072d39da43b767c932639da51264af1172c7322ba7ca105a5525d5705bL303-R303) [[3]](diffhunk://#diff-61d676072d39da43b767c932639da51264af1172c7322ba7ca105a55 …
=> Apim bugfixes

libraries/RW/K8sLog/k8s_log.py
This update introduces new health check patterns for Azure Service Bus in k8s_log.py, enhancing log analysis capabilities. The added patterns focus on connection recovery, idle timeout recovery, link lifecycle management, and reactor disposal, all categorized under a new "HealthyRecovery" category. Additionally, the log processing logic has been updated to track severity 5 items separately, ensuring clearer reporting of normal operational events that do not require action. This enhancement aims to improve monitoring and troubleshooting of Azure Service Bus interactions within Kubernetes workloads.
=> Add Azure Service Bus health patterns to K8sLog

codebundles/k8s-deployment-healthcheck/runbook.robot, libraries/RW/K8sLog/k8s_log.py
Enhance K8s deployment health checks by adding "HealthyRecovery" to default log pattern categories in runbook.robot. Update Azure Service Bus log patterns in k8s_log.py to remove unnecessary conditions and introduce a new pattern for Azure Cosmos DB connection establishment, improving log analysis capabilities and clarity in monitoring Azure services.
=> K8s Logging: additional safe log exclusion patterns

codebundles/k8s-deployment-healthcheck/runbook.robot, codebundles/k8s-deployment-healthcheck/runbook_patterns.json, codebundles/k8s-deployment-healthcheck/sli.robot, codebundles/k8s-deployment-healthcheck/sli_critical_patterns.json, libraries/RW/K8sLog/k8s_log.py
Enhance log analysis patterns in K8s deployment health checks by updating default exclusion patterns in runbook.robot and sli.robot to include additional log levels and service identifiers. Introduce a custom patterns file in the log analysis process to improve filtering accuracy. Update sli_critical_patterns.json to expand the list of excluded patterns for better log clarity and monitoring.
=> Log analysis filder additions

codebundles/k8s-deployment-healthcheck/runbook.robot, codebundles/k8s-deployment-healthcheck/workload_issues.sh
Enhance Kubernetes deployment health checks by improving issue title generation in runbook.robot and workload_issues.sh. The updates include more descriptive titles based on specific resource information and event reasons, as well as additional checks for common pod issues such as scheduling, volume mounts, and network configurations. This change aims to provide clearer insights into deployment issues and streamline troubleshooting processes.
=> Enhance Kubernetes deployment warning event titles

codebundles/azure-aks-triage/aks_cluster_health.sh
- Extract detailed error information from cluster status and agent pools when provisioning fails, providing comprehensive insights into issues.
- Improve issue title generation for provisioning failures, diagnostics settings, and autoscaling status to include specific cluster names for better context.
- Add checks for individual agent pool provisioning failures, allowing for more granular error reporting and troubleshooting guidance.
This update aims to improve the clarity and usefulness of error messages, facilitating more effective troubleshooting of AKS cluster issues.
=> Enhance AKS cluster health check script with detailed error reporting

codebundles/k8s-deployment-healthcheck/runbook_patterns.json, codebundles/k8s-deployment-healthcheck/sli_critical_patterns.json
Enhance log analysis patterns in Kubernetes deployment health checks by adding new telemetry failure patterns in runbook_patterns.json and sli_critical_patterns.json. This update aims to improve error detection and monitoring capabilities for telemetry operations, facilitating better troubleshooting and insights into system health.
=> log analysis exclusion updates

codebundles/k8s-deployment-healthcheck/sli.robot
Remove invalid emojis in log messages when deployment is scaled down
=> Update logs for scaled down deployments

codebundles/k8s-deployment-healthcheck/sli.robot
=> Fix  k8s/deployment scaledown issues

codebundles/k8s-postgres-operations/.runwhen/templates/k8s-postgres-operations-crunchy-slx.yaml, codebundles/k8s-postgres-operations/.runwhen/templates/k8s-postgres-operations-zalando-slx.yaml
Updates the database ops templates with valid icons
=> update database ops images

codebundles/k8s-stacktrace-health/runbook.robot, libraries/RW/LogAnalysis/traceback.py
temporary log inspection code added, will be reverted EOD.
=> stacktraceLogInTaskOutput: temp commit: add logs to report
