runwhen-contrib/rw-cli-codecollection

- codebundles/k8s-statefulset-healthcheck/runbook.robot
This only adds in the command_list render capabilities, but doesn't touch the rest of the logic. As we chatted about, the last task could be reworked possibly to support both use cases, but this is the fastest path towards command list integration for now.
> add cmd_list integration

- codebundles/k8s-artifactory-health/runbook.robot
- codebundles/k8s-deployment-healthcheck/runbook.robot
- libraries/RW/CLI/stdout_parser.py
- add triage taskset for artifactory
- Tweak stdout parser to assume no capture groups as a non-issue
- Make regexp argument optional, allowing users to just use the `_line` variable to raise issues on
> Add Artifactory Triage

- codebundles/k8s-jenkins-healthcheck/runbook.robot
Minor jenkins fixups to render additional commands in commandlist and fix up the curl response code output for command list interpretation. I've tested the runbook as is, and also with some runwhen-local fixups. 
I think I have an idea on how to handle the secrets / username / passwords - which helps to render more content in the troubleshooting command list:
> minor tuneups, runwhen_local optimization

- codebundles/gcloud-log-inspection/runbook.robot
- codebundles/k8s-jenkins-healthcheck/runbook.robot
- libraries/RW/CLI/json_parser.py
- libraries/RW/CLI/stdout_parser.py
- updates formatting in parsers to use template and `$var` syntax to avoid recursive json formatting, resulting in keyerrors
> Fix recursive json formatting

- codebundles/curl-gmp-ingress-inspection/README.md
- codebundles/curl-gmp-ingress-inspection/runbook.robot
- libraries/RW/CLI/json_parser.py
- libraries/RW/CLI/stdout_parser.py
- Adds a nginx ingress triage which lists the nginx ingress names, namespaces and associated services that returned the HTTP error codes detected in the metrics. Ideally personas can piggy back off the raised issue details to investigate those namespaces/services further
- Tweaks max issue string length to 512, I found it getting truncated too soon with the new templated variables in use
> Add nginx ingress inspection taskset

- codebundles/k8s-deployment-healthcheck/README.md
- codebundles/k8s-deployment-healthcheck/runbook.robot
- adds anomaly event task to taskset so it's more likely to be run at a smaller scope by assistants
- tweaks log fetch to raise issues when log results are found matching a error pattern (has include+exclude behaviour)
> Add task additions to k8s deploy taskset

- codebundles/aws-cloudwatch-overused-ec2/README.md
- codebundles/aws-cloudwatch-overused-ec2/runbook.robot
- libraries/RW/CLI/cli_utils.py
- adds a codebundle for raising issues for over-utilized EC2 instances using cloudwatch metrics
Note: putting together the EKS equivalent right now but I thought it'd be good to PR this so you can see the pattern/give feedback @stewartshea
> Add cloudwatch EC2 util check

- codebundles/aws-cloudwatch-overused-ec2/runbook.robot
- codebundles/cli-test/runbook.robot
- codebundles/cmd-test/runbook.robot
- codebundles/curl-gmp-nginx-ingress-inspection/runbook.robot
- codebundles/gcloud-log-inspection/runbook.robot
- codebundles/k8s-artifactory-health/runbook.robot
- codebundles/k8s-certmanager-healthcheck/runbook.robot
- codebundles/k8s-certmanager-healthcheck/sli.robot
- codebundles/k8s-daemonset-healthcheck/runbook.robot
- codebundles/k8s-deployment-healthcheck/runbook.robot
- codebundles/k8s-imagerollover-check/runbook.robot
- codebundles/k8s-jenkins-healthcheck/runbook.robot
- codebundles/k8s-namespace-healthcheck/runbook.robot
- codebundles/k8s-podresources-health/runbook.robot
- codebundles/k8s-redis-healthcheck/runbook.robot
- codebundles/k8s-statefulset-healthcheck/runbook.robot
- codebundles/k8s-vault-healthcheck/runbook.robot
- libraries/RW/CLI/json_parser.py
- libraries/RW/CLI/stdout_parser.py
- update author name to github handle format
- slightly reduces issue string max length as it turns out the API model has a max length of 2000, this was causing exceptions in the BOW index
> reformat authors and reduce max issue length to stop api model error

- .github/queries/addDiscussionComment.graphql
- .github/queries/createDiscussion.graphql
- .github/queries/deleteDiscussion.graphql
- .github/queries/getComments.graphql
- .github/queries/getDiscussion.graphql
- .github/queries/searchDiscussions.graphql
- .github/workflows/update-discussion.yml
This adds a workflow to create a github discussion for a new codebundle folder. 
Some of the code is not used yet, we might have future desire to expand the functionality, but for now this just checks if it exists, and if not, creates it. 
Beware of the #Temp for cleamup of messes header, it can be used to clean up a mess if we've created a lot of discussions incorrectly, but it's most likely not that helpful once we have a bunch of discussions with active comments.
> create gh discussions for codebundles

- .github/scripts/e2e.py
- .github/workflows/e2e.yml
- codebundles/k8s-redis-healthcheck/runbook.robot
- codebundles/k8s-vault-healthcheck/runbook.robot
- adds script to test applicable recently changed codebundles in a target workspace. They are chosen to run if: they were changed in the PR, and they are used in the target workspace
- Contains a runall option, with a passthrough config via workflow dispatch for manual call via the github UI
- A codebundle is considered a pass/succeed if it runs fully without throwing any exceptions
- polls results every 60 seconds until all tasksets finish, times out after 10m
Sample output:
TODO:
- dynamic ephemeral workspaces
- tracing python dependencies so that python keyword changes initiate tests for dependent codebundles
- QA on issue submission (difficult but an endgoal for a mature pipeline far in the future)
The above are 'nice-to-haves' as I feel this initial pass should get us most of the way …
> Initial e2e CI for codebundles

- codebundles/k8s-statefulset-healthcheck/runbook.robot
Add's some escape characters to the \n output; in the current form this breaks the command rendering in runwhen-local docs
> add escape characters to text output of ss replica

- codebundles/k8s-certmanager-healthcheck/README.md
- codebundles/k8s-certmanager-healthcheck/runbook.robot
adds commands for checking certificaterequests. Also adds a filter in the first task to only take into account objects with a renewalTime field - removing an error when certs are failed and do not have this field.
> Cert-manager-troubleshooting

- codebundles/k8s-argocd-application-health/runbook.robot
patches up some newlines that break the markdown rendering in runwhen-local
> escape newlines for argo codebundle

- Dockerfile
- codebundles/cmd-test/getdeploys.sh
- codebundles/cmd-test/runbook.robot
- libraries/RW/CLI/CLI.py
- libraries/RW/CLI/local_process.py
- libraries/RW/NextSteps/Kubernetes/mapping.yaml
- libraries/RW/NextSteps/Suggest.py
- libraries/RW/NextSteps/__init__.py
- requirements.txt
- Adds a troubleshooting lookup keyword that can "suggest" nextsteps based on a error bingo board, called `RW.NextSteps.Suggest`
- Adds `RW.NextSteps.Format` keyword to allow for quick injection of live object values/names into nextsteps message before issue submission to reduce robot bloat
- Board is based on a maintained static yaml mapping file, specific to each system/platform (eg: 1 for Kubernetes, 1 for ECS, 1 for Google Cloudrun, etc)
- Adds `RW.CLI.Run Bash File` keyword
See https://github.com/runwhen-contrib/rw-cli-codecollection/blob/err-bingo/codebundles/cmd-test/runbook.robot for samples
> Implement Error Bingo mapping for nextsteps generation

- codebundles/azure-loadbalancer-triage/README.md
- codebundles/azure-loadbalancer-triage/runbook.robot
- codebundles/azure-monitor-event-triage/README.md
- codebundles/azure-monitor-event-triage/runbook.robot
- codebundles/azure-monitor-event-triage/sli.robot
- codebundles/k8s-app-troubleshoot/README.md
- codebundles/k8s-app-troubleshoot/env_check.sh
- codebundles/k8s-app-troubleshoot/runbook.robot
- codebundles/k8s-restart-resource/README.md
- codebundles/k8s-restart-resource/runbook.robot
- Adds codebundle for triaging Azure internal loadbalancer errors
- Adds starter mvp for application troubleshooting on the platform
- Adds generalized azure monitor triage report and SLI for monitoring activity logs API as error metric
- Adds codebundle to restart kubernetes resources (using rollout to respect strategies), ideally recommended at the end of troubleshooting session
> Add application and Azure troubleshooting codebundles

- codebundles/k8s-certmanager-healthcheck/.runwhen/generation-rules/k8s-certmanager-certificates-health.yaml
- codebundles/k8s-certmanager-healthcheck/.runwhen/templates/k8s-certmanager-certificate-health-sli.yaml
- codebundles/k8s-certmanager-healthcheck/.runwhen/templates/k8s-certmanager-certificate-health-slx.yaml
- codebundles/k8s-certmanager-healthcheck/.runwhen/templates/k8s-certmanager-certificate-health-taskset.yaml
- codebundles/k8s-certmanager-healthcheck/sli.robot
- codebundles/k8s-loki-healthcheck/.runwhen/generation-rules/k8s-loki-healthcheck.yaml
- codebundles/k8s-loki-healthcheck/.runwhen/templates/k8s-loki-healthcheck-slx.yaml
- codebundles/k8s-loki-healthcheck/.runwhen/templates/k8s-loki-healthcheck-taskset.yaml
- codebundles/k8s-namespace-healthcheck/runbook.robot
- codebundles/k8s-prometheus-healthcheck/.runwhen/generation-rules/k8s-prometheus-healthcheck.yaml
- codebundles/k8s-prometheus-healthcheck/.runwhen/templates/k8s-prometheus-healthcheck-slx.yaml
- codebundles/k8s-prometheus-healthcheck/.runwhen/templates/k8s-prometheus-healthcheck-taskset.yaml
- loki genrules
- kubeprom genrules
- migrates certmanager genrules from kubectl-get to certmanager healthcheck codebundle
- consolidates certmanager related sli's into https://github.com/runwhen-contrib/rw-cli-codecollection/blob/main/codebundles/k8s-certmanager-healthcheck/sli.robot
TODO: remove genrules from rw-public as part of cleanup
> Bug fixes, task tweaks for certmanager and add genrules

- codebundles/k8s-kubectl-cmd/README.md
- codebundles/k8s-kubectl-cmd/runbook.robot
- codebundles/k8s-kubectl-cmd/sli.robot
adds a generic kubectl k8s codebundle. the other one in rw-public sort of forces the use of jmespath which is not ideal in all cases, so this one is more generic and relies on the user to ensure the output is a metric (for the sli) rather than providing a keyword to help.
> Kubectl generic

- codebundles/k8s-deployment-gitops-gh-remediate/runbook.robot
change var passing into script with triple quotes to avoid bash processing of the output that causes the recommendations to be filtered incorrectly.
> Fix k8s-deployment-gitops-remediate

- codebundles/k8s-namespace-healthcheck/README.md
- codebundles/k8s-namespace-healthcheck/runbook.robot
This task tends to provide duplicate error checking in which the issue output is radically close to other tasks. Currently it tends to create more noise that necessary.
> remove task

- libraries/RW/CLI/CLI.py
We were trying to run our mitigation script via [runbook.robot](https://github.com/infracloudio/ifc-rw-codecollection/blob/f/codebundle-rds-mysql-conn/codebundles/rds-mysql-conn-count/runbook.robot) using `RW.CLI.Run Bash File`.
Built this [Dockerfile](https://github.com/infracloudio/ifc-rw-codecollection/blob/f/codebundle-rds-mysql-conn/Dockerfile) and run docker container as follow and we set `RW_PATH_TO_ROBOT` env
```
docker run --rm -d -p 3000:3000 --name rds-codecollection \
--network="host" \
-e ENV_PROMETHEUS_HOST="http://af2ee8b74f89e4f8a83cd53d3745ccdc-1654255243.us-west-2.elb.amazonaws.com//prometheus/api/v1" \
-e ENV_QUERY="aws_rds_database_connections_average{dimension_DBInstanceIdentifier="robotshopmysql"} > 1" \
-e MYSQL_USER="admin" \
-e MYSQL_PASSWORD_ENV="<password>" \
-e …
```
> Support Running Bash Files from root or /app in 'run_bash_file' Function

- libraries/RW/CLI/local_process.py
This is mostly a workaround to support the use of proxies that require an internal CA until we move this logic into the platform (robot-runtime). It's not required, but it's much easier to allow the RunWhen Runner to set these values once by passing them through to the codebundle being executed than for the user to provide these for every SLX unless they are providing a unique CA via ConfigProvided & SecretsProvided via the SLX, in which case those values should take priority over the runner-provided values.
> feat(env): support global http(s) proxy passthrough with CAs

- codebundles/k8s-deployment-healthcheck/.runwhen/templates/k8s-deployment-health-taskset.yaml
- codebundles/k8s-deployment-healthcheck/runbook.robot
- codebundles/k8s-deployment-healthcheck/workload_issues.sh
- codebundles/k8s-deployment-healthcheck/workload_next_steps.sh
- codebundles/k8s-namespace-healthcheck/runbook.robot
- codebundles/k8s-namespace-healthcheck/workload_issues.sh
- codebundles/k8s-namespace-healthcheck/workload_next_steps.sh
- libraries/RW/K8sHelper/k8s_helper.py
Changes out the deployment and namespace health checks  to use dynamic issue detail generation for things like warning events, anomolies, etc. Still leaves the older workload_next_steps script in there which needs to be deprecated. This does generate *more* issues, but in theory the issue clustering should handle this. I tested in b-online-boutique for our standard test and it appeared to function well. We will need to test more in t-sandbox to determine if the noise is too much and we need additional noise reduction in the script.
> Minor touchups

- codebundles/aws-eks-health/.runwhen/templates/aws-eks-health-sli.yaml
- codebundles/aws-eks-health/.runwhen/templates/aws-eks-health-taskset.yaml
- codebundles/aws-eks-health/check_eks_cluster_health.sh
- codebundles/aws-eks-health/check_eks_fargate_cluster_health_status.sh
- codebundles/aws-eks-health/list_eks_fargate_metrics.sh
- codebundles/aws-eks-health/runbook.robot
- codebundles/aws-eks-health/sli.robot
- codebundles/aws-elasticache-redis-health/.runwhen/templates/aws-elasticache-redis-health-sli.yaml
- codebundles/aws-elasticache-redis-health/.runwhen/templates/aws-elasticache-redis-health-taskset.yaml
- codebundles/aws-elasticache-redis-health/analyze_aws_elasticache_redis_metrics.sh
- codebundles/aws-elasticache-redis-health/monitor_redis_performance.sh
- codebundles/aws-elasticache-redis-health/redis_status_scan.sh
- codebundles/aws-elasticache-redis-health/runbook.robot
- codebundles/aws-elasticache-redis-health/sli.robot
- codebundles/aws-lambda-health/.runwhen/templates/aws-lambda-health-sli.yaml
- codebundles/aws-lambda-health/.runwhen/templates/aws-lambda-health-taskset.yaml
- codebundles/aws-lambda-health/analyze_lambda_invocation_errors.sh
- codebundles/aws-lambda-health/list_lambda_runtimes.sh
- codebundles/aws-lambda-health/monitor_aws_lambda_performance_metrics.sh
- codebundles/aws-lambda-health/runbook.robot
- codebundles/aws-lambda-health/sli.robot
- codebundles/aws-s3-bucket-storage-report/.runwhen/templates/aws-s3-bucket-storage-report-taskset.yaml
- codebundles/aws-s3-bucket-storage-report/check_aws_s3_bucket_storage_utilization.sh
- codebundles/aws-s3-bucket-storage-report/runbook.robot
- rolls in the auth bash code into the scripts, this is due a design bug with subprocesses that only include the singular bash file in the environment, so `source` cant be used
- adds to genrules
- adds role arn secret to robot layer
> Enable AWS Role Assuming

- codebundles/k8s-otelcollector/.runwhen/generation-rules/k8s-otelcollector.yaml
- codebundles/k8s-otelcollector/.runwhen/templates/k8s-otelcollector-taskset.yaml
- codebundles/k8s-otelcollector/.runwhen/templates/k8s-otelcollector.yaml
- codebundles/k8s-otelcollector/README.md
- codebundles/k8s-otelcollector/otel_dropped_check.sh
- codebundles/k8s-otelcollector/otel_error_check.sh
- codebundles/k8s-otelcollector/otel_metrics_check.sh
- codebundles/k8s-otelcollector/runbook.robot
- adds taskset for checking the health of a otel collector (log errors scan, dropped items check, and checks queue metrics for large queues)
- supports various deployment modes of the helm chart
- assumes helm chart for genrules
> OpenTelemetry Collector Codebundle

- codebundles/k8s-deployment-ops/.runwhen/generation-rules/k8s-deployment-ops.yaml
Until persona ACLs are applied, these codebundles should only be manually added when desired
> Hide deployment Ops Manifests from Discovery

- codebundles/azure-aks-triage/aks_cluster_health.sh
- codebundles/azure-apim-health/gather_apim_resource_information.sh
- codebundles/azure-appservice-functionapp-health/appservice_config_health.sh
- codebundles/azure-appservice-webapp-health/appservice_config_health.sh
- codebundles/azure-servicebus-health/service_bus_config_health.sh
Configuration items moved to Severity 4 (Informational):
- TLS version settings
- Public network access policies
- HTTPS enforcement settings
- Service plan tier choices
- Managed identity assignments
- Zone redundancy preferences
- Autoscaling preferences
The rationale being while these are indeed incorrect configurations, the system will still be operational with the existence of these issue. Also these issues are straightforward to fix and do not require any further analysis to be done related to them.
> Update severity levels for various health checks across Azure resources to reflect informational status

- codebundles/k8s-podresources-health/runbook.robot
- Add defensive checks for empty stdout before JSON parsing
- Fix JSONDecodeError when no VPA resources exist in namespace
- Apply same pattern to overutilized pods task for consistency
- Initialize recommendation lists as empty arrays by default
- Prevent parsing empty strings that cause JSONDecodeError
The issue occurred when the vpa_recommendations.sh script output "No recommendations." and the awk command returned an empty string, which was then passed to json.loads() causing the error.
Fixes: JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> fix: handle empty JSON output in VPA recommendations task

- codebundles/k8s-stacktrace-health/runbook.robot
- codebundles/k8s-stacktrace-health/sli.robot
- libraries/RW/LogAnalysis/java/fetch_tracebacks.py
- libraries/RW/LogAnalysis/python/fetch_tracebacks.py
- libraries/RW/LogAnalysis/traceback.py
- using the keyword `fetch_workload_logs` from the library `RW.K8sLog` , the logs are dumped into a pod_container wise files in a temp directory.
- this directory is read by the `RW.LogAnalysis.ExtracTraceback` library and returns a unique list of tracebacks extracted across multiple programming languages.
> runbook fixed with new log fetch logic: dump logs into tmp_dir using RW.K8sLog library

- codebundles/k8s-stacktrace-health/runbook.robot
- libraries/RW/LogAnalysis/java/fetch_tracebacks.py
- Add try-catch block around log processing to handle malformed entries gracefully
- Implement final filtering to ensure returned stacktraces contain at least one "at" frame
- Remove debug logging from runbook to clean up output
- Improve robustness of stacktrace extraction process
> StacktraceLogInTaskOutput
